---
title: "Getting the data on small scale"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Getting the data on small scale}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r warning=FALSE, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(httr)
library(readr)
library(dplyr)
library(purrr)
library(ggplot2)
```

## Trams
Data was taken from API, with calls every 60 seconds (refresh rate of API), over 3 hours. Data limited to line 7. Data access date 07-02-2022

```r
collect_trams_from_api(
  line_number = 7, 
  time_interval = 60, 
  max_calls = 181, 
  output = "../data-raw/tram-7-3h.tsv"
  )
```
## Get bus & tram stops

Next step is to identify where the stops are. After api call we receive ugly nested list that I stored in JSON format.
```{r, get-stops-data-from-api}
url <- paste0(
  "https://api.um.warszawa.pl/api/action/dbstore_get?id=1c08a38c-ae09-46d2-8926-4f9d25cb0630",
  "&apikey=", Sys.getenv("UM_WAW_PERSONAL_API_KEY")
  )

przystanki <- GET(url)

przystanki <- content(przystanki)

# jsonlite::write_json(przystanki, "przystanki.json", pretty = TRUE)
```
That looks like this:
```json
{
  "result": [
    {
      "values": [
        {
          "value": ["1001"],
          "key": ["zespol"]
        },
        {
          "value": ["01"],
          "key": ["slupek"]
        },
        {
          "value": ["Kijowska"],
          "key": ["nazwa_zespolu"]
        },
        {
          "value": ["2201"],
          "key": ["id_ulicy"]
        },
        {
          "value": ["52.248455"],
          "key": ["szer_geo"]
        },
        {
          "value": ["21.044827"],
          "key": ["dlug_geo"]
        },
        {
          "value": ["al.Zieleniecka"],
          "key": ["kierunek"]
        },
        {
          "value": ["2021-10-08 00:00:00.0"],
          "key": ["obowiazuje_od"]
        }
      ]
    },
...
```

### CLEAN TRAMS GPS DATA
```{r echo=TRUE}
trams <- read_delim(
  file = "../data-raw/tram-7-3h.tsv",
  skip = 1, 
  col_names = FALSE,
  show_col_types = FALSE)

# remove row indexes
trams <- trams[2:ncol(trams)]

colnames(trams) <- c("line", "lon", "vehicle_number", "time", "lat", "brigade", "get_timestamp")

head(trams)
```

### CLEAN STOPS DATA
```{r}
przystanki <- jsonlite::read_json("przystanki.json")
key_names <- c("zespol", "slupek", "nazwa_zespolu", "id_ulicy", "szer_geo", "dlug_geo", "kierunek", "obowiazuje_od")
# get values for keys
przystanki_flat <- przystanki |> purrr::flatten() |> purrr::flatten()
przystanki_clean_list <- przystanki_flat |> 
  map(~map(.x, ~pluck(.x$value))) |>
  modify_depth(.depth = 1, ~ set_names(.x,nm = key_names))

# convert list to data.frame
przystanki_df <- przystanki_clean_list |> map_df(~unlist(.x))

english_keys <- c("team", "pole", "team_name", "street_id", "lat", "lon", "direction", "valid_from")
names(przystanki_df) <- english_keys

przystanki_df <- przystanki_df |> 
  mutate(
    lat = as.numeric(lat),
    lon = as.numeric(lon),
    valid_from = as.POSIXct(valid_from)
  )
przystanki_df |> head()

```

### Visualise data
```{r plot line 7}
trams |>
  ggplot(aes(x = lon, y = lat)) +
  geom_point(alpha = .1, show.legend = FALSE)

```

### Plot stops
```{r}
przystanki_df |>
  ggplot(aes(x = lon, y = lat)) +
  geom_point(alpha = .1, show.legend = FALSE)
```
